### ISSUE TITLE
Passing config_buffer option breaks with PyYAML6 due to extra required parameter

### ISSUE THREAD

**Issue by Hawk777** [zabertech/python-izaber#11]
In PyYAML 6, [the `pyyaml.load` function started requiring a second parameter](https://github.com/yaml/pyyaml/pull/561). `zconfig.YAMLConfig.load_config` calls that function if the `config_buffer` parameter is passed, and does not provide one, thus failing with PyYAML 6.

**Comment by amimoto** [comment]
Should be resolved

- Added regression test
- Switched to using `safe_load` rather than `pyyaml.load`. 
- Published `v3.0.20230207`
