### ISSUE TITLE
pytest-xdist should probably be in dev-dependencies

### ISSUE THREAD

**Issue by Hawk777** [zabertech/python-izaber#13]
`pytest-xdist` is in the `tool.poetry.dependencies` section. I suspect it probably belongs in the `tool.poetry.dev-dependencies` section; I doubt it’s needed by consumers?

**Comment by amimoto** [comment]
No. Whoops. Definitely shouldn't be in deps. Will fix.

**Comment by amimoto** [comment]
Thanks! This should be resolved now with `3.1.20230817`
